### ISSUE TITLE
Query Specific Data

### ISSUE THREAD

**Issue by DongDanBam** [buzz/mediainfo.js#51] opened 2021-02-17 01:55 UTC
I got an example working great.

Now Im trying to come up with a way to extract specific data.

For example. Frame rate.

Im thinking the syntax should be something like this with result.frameRate

`

 ```
       mediainfo
               .analyzeData(getSize, readChunk)
                .then((result) => {
                    consoleLog("Frame: "+ result.frameRate)
                    //output.value = result
                })
                .catch((error) => {
                    output.value = `An error occured:\n${error.stack}`
                })`
```
but I cant figure out the exact syntax. Can you help point me in the right direction?

**Comment by buzz** [comment] 2021-02-17 12:00
Duplicate of #49

**Closed by buzz** 2021-02-17 12:00 UTC
