### ISSUE TITLE
Duration does not have milliseconds information for videos over 1 minute.

### ISSUE THREAD

**Issue by wholeinsoul** [buzz/mediainfo.js#60] opened 2021-04-03 03:44 UTC
Hello,

The library does not return the milliseconds information for videos over 1 minute.

examples: 
**Actual -> Reported**
1.911s -> 1s 911ms
61.911s -> 1mn 1s      // miliseconds got truncated. expected was 1mn 1s 911ms

Is there any setting to obtain the complete duration including milliseconds.
Thanks.

**Comment by buzz** [comment] 2021-04-03 13:05
Please check with [MediaInfo](https://mediaarea.net/en/MediaInfo). If the issue is also present there, report the issue in the [upstream library](https://github.com/MediaArea/MediaInfoLib). In that case, please close this issue.

**Comment by JeromeMartinez** [comment] 2021-04-03 17:10
> Please check with MediaInfo.

In MediaInfo library, `Duration/String` (default) is like described, there are `Duration` with raw value in milliseconds, `Duration/String1` with 3 numbers, or [others](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Resource/Text/Stream/General.csv#L96-L102).

The result of `MediaInfo::Inform()` has the default and is not (yet) tweakable.

**Comment by wholeinsoul** [comment] 2021-04-03 17:18
Hi @buzz, @JeromeMartinez  it seems to work as expected in the demo that at https://mediainfo.js.org/ but not when I use it as a library.

**Comment by buzz** [comment] 2022-07-23 16:43
Using `full` option should always give access to milliseconds (#92).

**Closed by buzz** 2022-07-23 16:43 UTC
