### ISSUE TITLE
mediainfo.js does not resolve specific audio file duration

### ISSUE THREAD

**Issue by ErezDalet** [buzz/mediainfo.js#128] opened 2023-04-04 09:52 UTC
mediainfo.js used version: 0.1.9
I also tried with 'full' option set to true, 
this is the output I get:
```
{
    "creatingLibrary": {
        "name": "MediaInfoLib",
        "version": "22.09",
        "url": "https://mediaarea.net/MediaInfo"
    },
    "media": {
        "@ref": "",
        "track": [{
                "@type": "General",
                "Count": "331",
                "StreamCount": "1",
                "StreamKind": "General",
                "StreamKind_String": "General",
                "StreamKindID": "0",
                "AudioCount": "1",
                "Audio_Format_List": "AAC LC",
                "Audio_Format_WithHint_List": "AAC LC",
                "Audio_Codec_List": "AAC LC",
                "Format": "ADTS",
                "Format_String": "ADTS",
                "Format_Info": "Audio Data Transport Stream",
                "Format_Extensions": "aac aacp adts",
                "Format_Commercial": "ADTS",
                "FileSize": "210049",
                "FileSize_String": "205 KiB",
                "FileSize_String1": "205 KiB",
                "FileSize_String2": "205 KiB",
                "FileSize_String3": "205 KiB",
                "FileSize_String4": "205.1 KiB",
                "OverallBitRate_Mode": "VBR",
                "OverallBitRate_Mode_String": "Variable",
                "StreamSize": "0",
                "StreamSize_String": "0.00 Byte (0%)",
                "StreamSize_String1": " Byte0",
                "StreamSize_String2": "0.0 Byte",
                "StreamSize_String3": "0.00 Byte",
                "StreamSize_String4": "0.000 Byte",
                "StreamSize_String5": "0.00 Byte (0%)",
                "StreamSize_Proportion": "0.00000"
            }, {
                "@type": "Audio",
                "Count": "285",
                "StreamCount": "1",
                "StreamKind": "Audio",
                "StreamKind_String": "Audio",
                "StreamKindID": "0",
                "Format": "AAC",
                "Format_String": "AAC LC",
                "Format_Info": "Advanced Audio Codec Low Complexity",
                "Format_Commercial": "AAC",
                "Format_Version": "4",
                "Format_AdditionalFeatures": "LC",
                "CodecID": "2",
                "BitRate_Mode": "VBR",
                "BitRate_Mode_String": "Variable",
                "Channels": "1",
                "Channels_String": "1 channel",
                "ChannelPositions": "Front: C",
                "ChannelPositions_String2": "1/0/0",
                "ChannelLayout": "C",
                "SamplesPerFrame": "1024",
                "SamplingRate": "8000",
                "SamplingRate_String": "8 000 Hz",
                "FrameRate": "7.812",
                "FrameRate_String": "7.812 FPS (1024 SPF)",
                "Compression_Mode": "Lossy",
                "Compression_Mode_String": "Lossy",
                "StreamSize": "210049",
                "StreamSize_String": "205 KiB (100%)",
                "StreamSize_String1": "205 KiB",
                "StreamSize_String2": "205 KiB",
                "StreamSize_String3": "205 KiB",
                "StreamSize_String4": "205.1 KiB",
                "StreamSize_String5": "205 KiB (100%)",
                "StreamSize_Proportion": "1.00000"
            }
        ]
    }
}
```

When mediainfo desktop application is used, I'm able to get the duration when using Debug->full parsing.

desktop application output (with full parsing option):
```
{
"media": {
"@ref": "\\\\qa-dovi\\Shared\\Samples\\Audio\\A313_sample.AAC",
"track": [
{
"@type": "General",
"AudioCount": "1",
"FileExtension": "AAC",
"Format": "MPEG-4",
"CodecID": "M4V ",
"CodecID_Compatible": "M4V /mp42/isom",
"FileSize": "10349971",
"Duration": "871.143",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "95047",
"StreamSize": "158219",
"HeaderSize": "28",
"DataSize": "10191766",
"FooterSize": "158177",
"IsStreamable": "No",
"Encoded_Date": "UTC 2014-11-25 18:24:53",
"Tagged_Date": "UTC 2014-11-25 18:24:53",
"File_Created_Date": "UTC 2023-04-03 06:53:29.182",
"File_Created_Date_Local": "2023-04-03 09:53:29.182",
"File_Modified_Date": "UTC 2014-11-25 18:25:52.857",
"File_Modified_Date_Local": "2014-11-25 21:25:52.857",
"extra": {
"FileExtension_Invalid": "mov mp4 m4v m4a m4b m4p m4r 3ga 3gpa 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma ismt f4a f4b f4v"
}
},
{
"@type": "Audio",
"StreamOrder": "0",
"ID": "1",
"Format": "AAC",
"Format_AdditionalFeatures": "LC",
"CodecID": "mp4a-40-2",
"Duration": "871.143",
"Source_Duration": "871.143",
"BitRate_Mode": "VBR",
"BitRate": "96000",
"BitRate_Maximum": "320000",
"Channels": "2",
"ChannelPositions": "Front: L R",
"ChannelLayout": "L R",
"SamplesPerFrame": "1024",
"SamplingRate": "44100",
"SamplingCount": "38417408",
"FrameRate": "43.066",
"FrameCount": "37517",
"Source_FrameCount": "37517",
"Compression_Mode": "Lossy",
"StreamSize": "10191752",
"StreamSize_Proportion": "0.98471",
"Source_StreamSize": "10191750",
"Source_StreamSize_Proportion": "0.98471",
"Language": "en",
"Encoded_Date": "UTC 2014-11-25 18:24:53",
"Tagged_Date": "UTC 2014-11-25 18:24:53"
}
]
}
}
```

Is there a possibility to get the duration for this file?

sample:
[audio.zip](https://github.com/buzz/mediainfo.js/files/11147174/audio.zip)

**Comment by buzz** [comment] 2023-07-31 15:02
I can't reproduce this.

I diff the output of the CPP program `mediainfo -f audio.aac` (v23.07) with the output of `mediainfo.js --full audio.aac` (v0.2.0/MediaInfoLib v23.07). Both are the same except for the info on the file on the filesystem which is expected.

```diff
11a12,15
> Complete name                            : audio.aac
> File name extension                      : audio.aac
> File name                                : audio
> File extension                           : aac
32a37,38
> File last modification date              : 2015-04-27 08:25:34 UTC
> File last modification date (local)      : 2015-04-27 10:25:34
```
I don't get a duration at all for that file. You might want to ask about it in the [upstream MediaInfoLib issue tracker](https://github.com/MediaArea/MediaInfoLib/issues).

Closing as this doesn't seem to be an issue with mediainfo.js.

**Closed by buzz** 2023-07-31 15:02 UTC
Labels: bug
