### ISSUE TITLE
Error instantiating MediaInfo (WebAssembly Compile error)

### ISSUE THREAD

**Issue by dcfranca** [buzz/mediainfo.js#63] opened 2021-04-27 12:46 UTC
Hi,
I'm new on using this library, and I was following the instructions to install and the examples provided and integrating it on my application.
I have a React application, already with a drag/drop mechanism for uploading videos, so I thought it would be a matter of copy/paste the example with a few changes:

I have installed mediainfo.js using yarn
`yarn add mediainfo.js`

Then added the following code

```
          import MediaInfo from 'mediainfo.js';

          const readChunk = (file) => (chunkSize, offset) =>
             new Promise((resolve, reject) => {
                const reader = new FileReader()
                reader.onload = (event) => {
                if (event.target.error) {
                   reject(event.target.error)
                }
                resolve(new Uint8Array(event.target.result))
             }
             reader.readAsArrayBuffer(file.slice(offset, offset + chunkSize))
           });
          ...
          MediaInfo().then((mediainfo) =>
            mediainfo
            .analyzeData(() => file.size, readChunk(file))
            .then((result) => {
              console.log('RESULT', result);
            })
            .catch((error) => {
              console.log('ERROR', error);
            })
        )
```
I had set breakpoints on both `then` and `catch`, but none are being called, instead I get the errors below:

Chrome:
```
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
arg0:CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0 
```

Firefox:
```
 instrument.js:138
Uncaught (in promise) RuntimeError: abort(CompileError: wasm validation error: at offset 4: failed to match magic number). Build with -s ASSERTIONS=1 for more info
```

Eventually, Firefox gives me a stack trace:
```
Unhandled Rejection (CompileError): wasm validation error: at offset 4: failed to match magic number
instantiateArrayBuffer/<
node_modules/mediainfo.js/dist/mediainfo.js:633
promise callback*instantiateArrayBuffer
node_modules/mediainfo.js/dist/mediainfo.js:632
instantiateAsync/</<
node_modules/mediainfo.js/dist/mediainfo.js:649
promise callback*instantiateAsync/<
node_modules/mediainfo.js/dist/mediainfo.js:646
promise callback*instantiateAsync
node_modules/mediainfo.js/dist/mediainfo.js:644
createWasm
node_modules/mediainfo.js/dist/mediainfo.js:667
./node_modules/mediainfo.js/dist/mediainfo.js/</</Module</<
node_modules/mediainfo.js/dist/mediainfo.js:2936
MediaInfoFactory
node_modules/mediainfo.js/dist/mediainfo.js:3328
MediaInfoFactory/<
node_modules/mediainfo.js/dist/mediainfo.js:3305
MediaInfoFactory
node_modules/mediainfo.js/dist/mediainfo.js:3304
<<<My code here>>>
```

I know that it requires `wasm` libraries, but do I need to do some extra steps to install it?

I've tried it on:
Firefox 87.0
Chrome 90.0.4430.85
mediainfojs 0.1.5

**Comment by buzz** [comment] 2021-04-27 15:30
Duplicate of #32.

Usage is described in [README.md](https://github.com/buzz/mediainfo.js#browser):

> The WASM module is loaded automatically and needs to be made available from the same location mediainfo.js is served from. This is the case for the CDN version. If you're using a bundler, you need to take care of this yourself. There are examples for React/webpack and Angular on how to achieve this.

**Closed by buzz** 2021-04-27 15:30 UTC
Labels: question
